skip-check:
  # Helm charts use dynamic parameterization (Checkov false positives on static eval)
  - CKV_K8S_14 # Image Tag should be fixed
  - CKV_K8S_21 # The default namespace should not be used
  - CKV_K8S_43 # Image should use digest

  # Prototyping allows env var secrets instead of mounted file volumes
  - CKV_K8S_35 # Prefer using secrets as files over secrets as environment variables

  # K8S network policies are evaluated poorly by Checkov against raw rendered Helm templates
  - CKV2_K8S_6 # Minimize the admission of pods which lack an associated NetworkPolicy
