apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-allowlist
data:
  allowlist.yaml: |
    admins:
{{- range .Values.adminAllowlist }}
      - {{ . | quote }}
{{- end }}
    # Future roles can be added here
