{{- if .Values.rustfs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  labels:
    app: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
      - name: rustfs
        image: {{ .Values.rustfs.image | quote }}
        env:
        - name: RUSTFS_ADDRESS
          value: ":9000"
        - name: RUSTFS_CONSOLE_ADDRESS
          value: ":9001"
        - name: RUSTFS_CONSOLE_ENABLE
          value: "false"
        - name: RUSTFS_VOLUMES
          value: "/data"
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-auth-secret
              key: accessKey
        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-auth-secret
              key: secretKey
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rustfs-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rustfs.persistence.size | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: api
  selector:
    app: rustfs


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rustfs-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    app: rustfs
spec:
  podSelector:
    matchLabels:
      app: rustfs
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: agent-substrate
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- end }}
