apiVersion: apps/v1
kind: Deployment
metadata:
  name: atecontroller
  labels:
    {{- include "agent-substrate.labels" . | nindent 4 }}
    app.kubernetes.io/component: atecontroller
spec:
  replicas: {{ .Values.atecontroller.replicaCount }}
  selector:
    matchLabels:
      {{- include "agent-substrate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: atecontroller
  template:
    metadata:
      labels:
        {{- include "agent-substrate.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: atecontroller
    spec:
      serviceAccountName: agent-substrate-controller-sa

      {{- with .Values.atecontroller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.atecontroller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.atecontroller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: atecontroller
        image: "{{ .Values.atecontroller.image.repository }}:{{ .Values.atecontroller.image.tag | default .Values.global.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.atecontroller.image.pullPolicy | default "IfNotPresent" }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.atecontroller.resources | nindent 10 }}

        command: ["/usr/local/bin/atecontroller"]
        args:
        - "--ateapi-conn-spec=ateapi:50051"
        - "--ateapi-client-cert=/etc/tls/bundle.pem"
        - "--ateapi-ca-file=/etc/tls/bundle.pem"
        - "--ateapi-server-name=ateapi"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.pod.uid=$(POD_UID),service.instance.id=$(POD_UID)
        volumeMounts:
        - name: tls
          mountPath: /etc/tls
          readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: agent-substrate-tls # pragma: allowlist secret
